feat: add mjs support
webpack/webpack-cli pull request #1786
Opened 2020-09-04 03:43 UTC by rishabh3112

**What kind of change does this PR introduce?**
Support for `.mjs` configs

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**
It is extension of @anshumanv's PR with support for esm configs using `esm` package.

**Does this PR introduce a breaking change?**

**Other information**
The standard `await import()` will not work as https://github.com/nodejs/node/pull/32985 has been reverted.
Using `esm` package in this PR to have esm interop

2020-09-05 13:15 UTC, evenstensberg commented on test/config-format/mjs/webpack.config.mjs
> +
remove these

2020-09-05 13:15 UTC, evenstensberg commented on test/config-format/mjs/webpack.config.mjs
> +const config = {
export default { ... }

2020-09-05 14:47 UTC, evenstensberg requested changes
Tests are failing

2020-09-13 03:40 UTC, rishabh3112 commented
> Tests are failing

@evenstensberg Yes, because `esm` package is not working properly here. I couldn't find upon investigation on how to make it work.
So, I need help.

2020-09-21 15:29 UTC, evilebottnawi commented
I think we don't need package, we can use this idea https://github.com/gulpjs/gulp-cli/blob/master/lib/shared/require-or-import.js

2020-09-21 16:59 UTC, rishabh3112 commented
> I think we don't need package, we can use this idea https://github.com/gulpjs/gulp-cli/blob/master/lib/shared/require-or-import.js

Same not working again locally.

2020-09-21 17:04 UTC, evilebottnawi commented
@rishabh3112 what is node you are use (version)?

2020-09-21 17:06 UTC, rishabh3112 commented
Tried on 12, 13 and 14. (I use fnm)

2020-09-21 17:08 UTC, evilebottnawi commented
Maybe something broken in `fnm`? I use `nvm` and tests for gulp-cli worked with mjs

2020-09-21 17:12 UTC, rishabh3112 commented
> Maybe something broken in fnm? .

Can't say for sure. Lets see CI, if still not passed then can you try checking out this branch and testing locally once?

2020-09-21 17:13 UTC, anshumanv commented
I tried with nvm in the past, no luck 😞

2020-09-21 17:13 UTC, anshumanv commented
Yep would be great if @evilebottnawi can check once

2020-12-03 12:51 UTC, closed without merging