chore: remove packages tests and bump versions
webpack/webpack-cli pull request #1798
Opened 2020-09-11 20:18 UTC by evenstensberg

**What kind of change does this PR introduce?**

Updates dependencies for master branch and disables building and testing reduntant monorepo packages

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
N/A
**Summary**

Se first point

**Does this PR introduce a breaking change?**

No
**Other information**
N/A

2020-09-12 13:03 UTC, evilebottnawi reviewed
Why?

2020-09-12 13:04 UTC, evilebottnawi commented on package.json
> +    "pretest": "npm run lint",
Don't touch this

2020-09-12 13:04 UTC, evilebottnawi commented on package.json
> +      "bin/**.js"
Don't touch this, it should be done in PR where we store coverage after removing all tests between v3 and v4

2020-09-12 13:04 UTC, evilebottnawi commented on package.json
> +      "/packages/"
https://github.com/webpack/webpack-cli/pull/1798/files#r487407963

2020-09-12 13:05 UTC, evenstensberg commented
Monorepo fails to build, we don't need to build monorepo for a downstream

2020-09-12 13:14 UTC, evilebottnawi commented
@evenstensberg Can you clarify?

2020-09-12 13:16 UTC, evenstensberg commented
Try running npm test on master

2020-09-23 04:13 UTC, rishabh3112 requested changes
Is this PR required now?

2020-09-23 10:47 UTC, evilebottnawi commented
I think we don't need it

2020-10-07 13:57 UTC, closed without merging