refactor: external command
webpack/webpack-cli pull request #1867
Opened 2020-10-04 10:48 UTC by rishabh3112

**What kind of change does this PR introduce?**
refactor

**Did you add tests for your changes?**
Updated them

**If relevant, did you update the documentation?**
N/A

**Summary**
Part of refactors moving away from group design

**Does this PR introduce a breaking change?**
No

**Other information**
N/A

2020-10-04 11:15 UTC, snitin315 approved these changes

2020-10-05 09:59 UTC, evilebottnawi approved these changes

2020-10-05 12:07 UTC, jamesgeorge007 requested changes
Please resolve the conflicts.

2020-10-06 10:02 UTC, evilebottnawi approved these changes
/cc @webpack/cli-team

2020-10-06 10:04 UTC, snitin315 approved these changes

2020-10-06 10:32 UTC, jamesgeorge007 approved these changes

2020-10-06 10:35 UTC, merged