chore: use default timeout for loader and plugin
webpack/webpack-cli pull request #1892
Opened 2020-10-07 11:51 UTC by rishabh3112

**What kind of change does this PR introduce?**
chore

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
N/A

**Summary**
Using default timeout which is `240000` instead of `60000`(in ms)

**Does this PR introduce a breaking change?**
No

**Other information**
These tests fail randomly on macos ci

2020-10-07 12:17 UTC, snitin315 submitted a review, later dismissed

2020-10-07 13:56 UTC, evenstensberg submitted a review, later dismissed

2020-10-07 14:06 UTC, evilebottnawi submitted a review, later dismissed

2020-10-07 17:01 UTC, anshumanv requested changes
Can you also remove it in - 

- test/migrate/config/migrate-config.test.js
- test/config-format/typescript/typescript.test.js
- test/entry/scss/scss.test.js

2020-10-08 04:09 UTC, snitin315 approved these changes

2020-10-08 10:15 UTC, evilebottnawi approved these changes

2020-10-08 10:16 UTC, evilebottnawi commented
/cc @anshumanv

2020-10-08 10:28 UTC, anshumanv approved these changes

2020-10-08 10:31 UTC, merged