tests: enable --analyze tests for windows
webpack/webpack-cli pull request #1894
Opened 2020-10-07 14:21 UTC by snitin315

**What kind of change does this PR introduce?**
tests

**Did you add tests for your changes?**
yes
**If relevant, did you update the documentation?**
No
**Summary**
fix for windows.

**Does this PR introduce a breaking change?**
No

**Other information**
No

2020-10-07 14:32 UTC, evilebottnawi submitted a review, later dismissed

2020-10-07 16:13 UTC, rishabh3112 requested changes
Nice Job! 
Left a small suggestion.`main.js` is default output of `webpack`, should keep file names less ambiguous in tests.

2020-10-07 16:13 UTC, rishabh3112 commented on test/analyze/webpack.config.js
> +    entry: './src/main.js',
```suggestion
```

2020-10-07 16:13 UTC, rishabh3112 commented on test/analyze/src/main.js
> +console.log('analyze flag test');
Make `src/index.js` file instead.

2020-10-08 01:18 UTC, snitin315 commented on test/analyze/webpack.config.js
> +    entry: './src/main.js',
done

2020-10-08 01:19 UTC, snitin315 commented on test/analyze/src/main.js
> +console.log('analyze flag test');
Done

2020-10-08 04:35 UTC, rishabh3112 approved these changes

2020-10-08 10:12 UTC, evilebottnawi approved these changes

2020-10-08 10:13 UTC, merged