chore: add peer dependencies for yarn pnp
webpack/webpack-cli pull request #1941
Opened 2020-10-14 06:06 UTC by aicest

**What kind of change does this PR introduce?**

bugfix: fix `peerDependencies` for Yarn PnP.

**Did you add tests for your changes?**

no.

**If relevant, did you update the documentation?**

no.

**Summary**

Support Yarn PnP.

1. `@webpack-cli/serve` require `webpack-dev-server`(a peer dependency);
2. `webpack-cli` require `@webpack-cli/serve`;
3. so, `webpack-cli` need to add `webpack-dev-server` into `peerDependencies`.

**Does this PR introduce a breaking change?**

no.

**Other information**

![image](https://user-images.githubusercontent.com/4016742/95949642-ad5c0580-0e25-11eb-998b-a15ea2e15883.png)

2020-10-14 06:21 UTC, snitin315 commented on packages/webpack-cli/package.json
> +    "webpack-dev-server": "3.x.x"
Maybe add it in `peerDependenciesMeta`?

2020-10-14 11:14 UTC, evilebottnawi requested changes
This will not fix your problem, please read again the message, you are trying to fix in `webpack-cli` package, but problems in `@webpack-cli/serve`, but you can use what it is fixed, double check your versions

2020-10-14 12:52 UTC, aicest commented
@evilebottnawi IT WILL ([I DID TRY](https://github.com/aicest/webpack-v5-demo)).

`@webpack-cli/serve` require a peer dependency (neither `devDependencies ` nor `dependencies`),
and `webpack-cli` require `@webpack-cli/serve`,
then `webpack-cli` should add the dependency (to `devDependencies/dependencies` or `peerDependencies`).

P.S. Another solution: `@webpack-cli/serve` add `webpack-dev-server` to `devDependencies/dependencies` (not a peer dependency).

2020-10-14 13:01 UTC, evilebottnawi commented
webpack-dev-server should be not in `dependencies`, `devDependencies` will not work for your

2020-10-14 13:03 UTC, evilebottnawi commented
https://github.com/webpack/webpack-cli/blob/master/packages/serve/package.json#L19

2020-10-14 13:08 UTC, ylemkimon commented
@evilebottnawi Actually, this would be the right way to solve it. See #1825 and https://yarnpkg.com/advanced/error-codes/#yn0002---missing_peer_dependency.

Dependency tree (D: dependency, P: peer dependency, PM: optional peer dependency, *: added in this PR, **: reason):
```
webpack-cli
├─P> webpack
├─PM> webpack-dev-server*
├─D> @webpack-cli/info
│    └─P> webpack-cli
├─D> @webpack-cli/init
│    ├─P> webpack
│    ├─P> webpack-cli
│    ├─D> @webpack-cli/generators
│    │    ├─P> webpack
│    │    ├─P> webpack-cli
│    │    ├─D> @webpack-cli/utils
│    │    │    ├─P> webpack
│    │    │    └─P> webpack-cli
│    │    └─D> @webpack-cli/webpack-scaffold
│    └─D> @webpack-cli/utils
│         ├─P> webpack
│         └─P> webpack-cli
└─D> @webpack-cli/serve
     ├─P> webpack-cli
     └─PM> webpack-dev-server**
```
 
This will work out of the box, since Yarn 2 falls back to root dependency and `webpack-dev-server` is usually root dependency, but in case of `pnpFallbackMode: none` and workspaces, the fix is required.

2020-10-14 13:12 UTC, evilebottnawi commented
webpack-cli doesn't use `webpack-dev-server`, it is not fixed your problem

2020-10-14 13:16 UTC, ylemkimon commented
> webpack-cli doesn't use `webpack-dev-server`, it is not fixed your problem

However, `@webpack-cli/serve`, a dependency of `webpack-cli`, optionally requires `webpack-dev-server`, so `webpack-dev-server` should be declared as an optional peer dependency for Yarn to properly resolve dependency tree.

2020-10-14 13:22 UTC, evilebottnawi commented
/cc @arcanis

2020-10-14 13:29 UTC, arcanis commented
From what I understand of the situation, @ylemkimon is correct - peer dependencies must be referenced at every level of the dependency chain, even in the intermediary packages that don't use it themselves. Cf this [article](https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0) I wrote about this some time ago.

2020-10-14 13:36 UTC, evilebottnawi approved these changes

2020-10-14 13:37 UTC, evilebottnawi commented
@ylemkimon Please accept CLA

2020-10-14 13:40 UTC, ylemkimon commented
@aicest is the author :smile:

2020-10-14 13:40 UTC, evilebottnawi commented
@aicest Can you accept CLA?

2020-10-14 13:58 UTC, snitin315 approved these changes

2020-10-15 06:33 UTC, aicest commented
@evilebottnawi CLA accepted.

2020-10-15 06:36 UTC, anshumanv approved these changes

2020-10-15 11:31 UTC, closed without merging

2020-10-15 11:37 UTC, evilebottnawi commented
@aicest sorry, it was fixed in other PR, anyway big thanks for the PR