chore: display running webpack version during tests
webpack/webpack-cli pull request #2026
Opened 2020-11-02 15:28 UTC by anshumanv

**What kind of change does this PR introduce?**

chore

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
NA

**Summary**
This display running webpack version during tests, useful to check if the CI cache is working correctly and locally to ensure we're running tests on correct env.

**Does this PR introduce a breaking change?**
No

**Other information**

2020-11-02 15:29 UTC, evilebottnawi approved these changes
Thanks

2020-11-02 15:29 UTC, evilebottnawi commented
Let's see versions on CI and merge if it will be fine

2020-11-02 17:56 UTC, evenstensberg submitted a review, later dismissed

2020-11-03 03:35 UTC, rishabh3112 requested changes
Need CI fix. `--progress=profile` test is failing.

2020-11-03 05:44 UTC, anshumanv commented
yep wip

2020-11-03 07:41 UTC, rishabh3112 submitted a review, later dismissed

2020-11-03 08:01 UTC, snitin315 commented on scripts/globalSetup.js
> +module.exports = () => console.log(`Running tests for webpack @${version}`);
Can we improve its visibility? 

![Screenshot at 2020-11-03 13-28-39](https://user-images.githubusercontent.com/46647141/97961088-a139e700-1dd8-11eb-8b73-62b261cf8694.png)

```suggestion
module.exports = () => console.log(`Running tests for webpack @${version}`);
```
```suggestion
module.exports = () => console.log(`\n Running tests for webpack @${version} \n`);
```

2020-11-03 08:26 UTC, snitin315 approved these changes

2020-11-03 08:30 UTC, rishabh3112 approved these changes

2020-11-03 08:38 UTC, merged