fix: warn the user if the JSON stats file already exists
webpack/webpack-cli pull request #2152
Opened 2020-12-01 02:15 UTC by snitin315

**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
Yes
**If relevant, did you update the documentation?**
No
**Summary**
 warn the user if the JSON stats file already exists.

`file 'stats.json' already exists. CLI will overwrite the existing file.`

**Does this PR introduce a breaking change?**
No

**Other information**
No

2020-12-01 08:07 UTC, rishabh3112 requested changes
Left a few suggestions.
Maintain immutability.
Use simple sentences wherever possible.

2020-12-01 08:07 UTC, rishabh3112 commented on packages/webpack-cli/lib/webpack-cli.js
> +                        logger.info(`file '${args.json}' already exists. CLI will overwrite the existing file.`);
```suggestion
                        logger.info(`file '${args.json}' already exists and will be overwritten.`);
```

2020-12-01 08:07 UTC, rishabh3112 commented on test/json/json.test.js
> +        expect(stdout).toContain(`file 'stats.json' already exists. CLI will overwrite the existing file.`);
```suggestion
        expect(stdout).toContain(`file 'stats.json' already exists and will be overwritten.`);
```

2020-12-01 08:07 UTC, rishabh3112 commented on test/json/json.test.js
> +        let { stdout, exitCode } = run(__dirname, ['--json', 'stats.json']);
```suggestion
       run(__dirname, ['--json', 'stats.json']);
```

2020-12-01 08:09 UTC, rishabh3112 requested changes

2020-12-01 08:09 UTC, rishabh3112 commented on test/json/json.test.js
> +        ({ stdout, exitCode } = run(__dirname, ['--json', 'stats.json']));
```suggestion
        const { stdout, exitCode } = run(__dirname, ['--json', 'stats.json']);
```

2020-12-01 08:14 UTC, snitin315 commented on packages/webpack-cli/lib/webpack-cli.js
> +                        logger.info(`file '${args.json}' already exists. CLI will overwrite the existing file.`);
Yeah It's better.

2020-12-01 08:16 UTC, snitin315 commented on test/json/json.test.js
> +       run(__dirname, ['--json', 'stats.json']);
```suggestion
        run(__dirname, ['--json', 'stats.json']);
```

2020-12-01 11:30 UTC, alexander-akait commented on packages/webpack-cli/lib/webpack-cli.js
> +                        logger.info(`file '${args.json}' already exists and will be overwritten.`);
`logger. warn`

2020-12-01 11:34 UTC, snitin315 commented on packages/webpack-cli/lib/webpack-cli.js
> +                        logger.info(`file '${args.json}' already exists and will be overwritten.`);
```suggestion
                        logger.warn(`file '${args.json}' already exists and will be overwritten.`);
```

2020-12-01 11:41 UTC, alexander-akait commented on test/json/json.test.js
> +        run(__dirname, ['--json', 'stats.json']);
We should check `exitCode`/`stderr`/`stdout` here too

2020-12-01 11:42 UTC, alexander-akait commented on test/json/json.test.js
> +        run(__dirname, ['--json', 'stats.json']);
As I said each tests should check `exitCode`/`stderr`/`stdout`

2020-12-01 13:03 UTC, alexander-akait reviewed
Should be merged after https://github.com/webpack/webpack-cli/pull/2144, approved

2020-12-01 14:54 UTC, alexander-akait reviewed
hm, what about if you in watch mode, it is expected behavior, and warning will be like a spam

2020-12-02 01:51 UTC, snitin315 commented
Just found `--watch` is not working as expected with `--json`. 
![Screenshot at 2020-12-02 07-20-18](https://user-images.githubusercontent.com/46647141/100817838-dd5f7680-346e-11eb-9c94-7cd078acd7b7.png)

because we don't continue to print stats after passing `--json`

2020-12-02 11:21 UTC, alexander-akait commented
Ideally it should work, we need `--interactive` for this

2020-12-02 11:24 UTC, snitin315 commented
Its working just stats are not being logged.

2020-12-02 11:39 UTC, alexander-akait commented
We can add workaround for watch and --json, we just should remove all from screen before printing them again

2021-01-09 14:31 UTC, alexander-akait commented
/cc @snitin315 Let's finish it - let's use async API (we already in async function, should be easy) + I think we should not output warning here, because it will be problem for `--watch`, maybe we should output only on first run

2021-01-09 14:56 UTC, snitin315 commented
@alexander-akait can you clarify what should be the expected behavior?

2021-01-09 15:03 UTC, alexander-akait commented
When you have file on first run we should log to user about file exists and it will be override, for other callbacks we should not log this + avoid using sync API

2021-01-09 15:19 UTC, snitin315 commented
I'm not sure how to achieve this behavior here - 

https://github.com/webpack/webpack-cli/blob/caa3348a825dfc5e0c6320304a28ce49630052ef/packages/webpack-cli/lib/webpack-cli.js#L1288-L1303

2021-01-09 15:31 UTC, alexander-akait reviewed
Pseudo core

```
if (isFirstRun && (await stats(args.json))) {
  logger.warn(`file '${args.json}' already exists and will be overwritten.`);
}

await writeFile(args.json, JSONStats);

isFirstRun = true;
```

2021-04-23 11:28 UTC, closed without merging