docs: synchronize webpack-4 options with help output
webpack/webpack-cli pull request #2307
Opened 2021-01-05 04:46 UTC by snitin315

**What kind of change does this PR introduce?**
docs

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
yes
**Summary**
sync options.
new added `--watch-options-stdin` and `--no-watch-options-stdin`

**Does this PR introduce a breaking change?**
No

**Other information**
No

2021-01-05 05:14 UTC, chenxsan commented on packages/webpack-cli/README.md
> +  info|i [options]                           Outputs information about your system.
```suggestion
  info|i [options]                           Output information about your system.
```

2021-01-05 05:15 UTC, chenxsan commented on packages/webpack-cli/README.md
> +  --mode <value>             Defines the mode to pass to webpack.
```suggestion
  --mode <value>             Define the mode to pass to webpack.
```

2021-01-05 12:03 UTC, alexander-akait requested changes
No need, `info` command `outputs ...`, focus on bugs and features

2021-01-06 12:41 UTC, alexander-akait requested changes
Again all options and commands should ends on `s`, look at schema in webpack

2021-01-06 12:49 UTC, chenxsan commented
> Again all options and commands should ends on `s`, look at schema in webpack

The convention I saw more is not to add `s`, e.g., https://docs.npmjs.com/cli/v6/commands.

Or `man find`:

```
```
![image](https://user-images.githubusercontent.com/1091472/103770243-a299c100-5060-11eb-94ef-67608ff26889.png)

2021-01-06 13:00 UTC, alexander-akait commented
We need discussion about this, because all webpack options uses `s`, I don't want to fix it in only one place, description for webpack options inside webpack core

2021-01-06 13:17 UTC, snitin315 commented
Yeah, let's keep only docs update and not change descriptions for now.

2021-01-21 20:45 UTC, evenstensberg approved these changes

2021-02-02 12:18 UTC, snitin315 commented
fixed in master

2021-02-02 12:18 UTC, closed without merging