Fixed a broken link to this repository
webpack/webpack-cli pull request #2597
Opened 2021-04-05 17:51 UTC by ibraheemalayan

the old url :  https://github.com/webpack-cli leads to a 404 page 
new url :  https://github.com/webpack/webpack-cli is the right one I think

2021-04-05 17:55 UTC, anshumanv approved these changes

2021-04-05 17:58 UTC, alexander-akait approved these changes

2021-04-05 19:01 UTC, anshumanv requested changes
Need update snapshots

2021-04-05 20:31 UTC, evenstensberg approved these changes
lgtm

2021-04-05 20:32 UTC, evenstensberg commented
@anshumanv maybe you could do this?

2021-04-05 20:32 UTC, anshumanv commented
yep will do 👍

2021-04-06 00:53 UTC, snitin315 commented
no worries I took care in #2600

2021-04-06 11:16 UTC, closed without merging

2021-04-06 11:17 UTC, alexander-akait commented
Fixed https://github.com/webpack/webpack-cli/pull/2600, thanks for PR