test: update
webpack/webpack-cli pull request #2668
Opened 2021-04-26 09:52 UTC by cap-Bernardito

**What kind of change does this PR introduce?**

tests added
Improve code coverage

**Does this PR introduce a breaking change?**

No

**Other information**

No

2021-04-26 10:53 UTC, snitin315 approved these changes

2021-04-26 14:00 UTC, jamesgeorge007 requested changes
Left a couple of suggestions

2021-04-26 14:00 UTC, jamesgeorge007 commented on test/api/capitalizeFirstLetter.test.js
> +    it('should return empty string, when passed not string value', () => {
```suggestion
    it('should return an empty string on passing a non-string value.', () => {
```

2021-04-27 19:03 UTC, evenstensberg approved these changes
lgtm

2021-04-28 00:43 UTC, snitin315 approved these changes

2021-04-28 04:40 UTC, jamesgeorge007 approved these changes

2021-04-28 04:41 UTC, merged