feat: configure workbox-webpack-plugin as opted
webpack/webpack-cli pull request #2722
Opened 2021-05-16 08:16 UTC by jamesgeorge007

**What kind of change does this PR introduce?**
Feature

**Did you add tests for your changes?**
WIP

**If relevant, did you update the documentation?**
WIP

**Summary**
#2430
[workbox-webpack-plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin)

**Does this PR introduce a breaking change?**
No

**Other information**
N/A

2021-05-17 09:12 UTC, rishabh3112 requested changes
Left few recommendations.

2021-05-17 12:07 UTC, evenstensberg commented on packages/generators/init-template/default/webpack.configjs.tpl
> +<% } %><% if (workboxWebpackPlugin) { %>
why? It's good for development too

2021-05-17 12:16 UTC, alexander-akait reviewed
Let's fix tests, I think for ideal testing we should run webpack after create configuration so we will ensure all works fine, but let's it improve in future PRs

2021-05-18 23:07 UTC, evenstensberg approved these changes
lgtm, even though PWA can be in dev mode too

2021-05-19 11:03 UTC, alexander-akait approved these changes

2021-05-19 11:03 UTC, merged

2021-05-19 11:03 UTC, alexander-akait commented
Thanks