fix: close compiler on SIGINT
webpack/webpack-cli pull request #2919
Opened 2021-08-25 11:18 UTC by snitin315

**What kind of change does this PR introduce?**
fix

**Did you add tests for your changes?**
No
**If relevant, did you update the documentation?**
No
**Summary**

Fix #2918 

**Does this PR introduce a breaking change?**
None

**Other information**
No

2021-08-25 11:25 UTC, alexander-akait commented on packages/webpack-cli/lib/webpack-cli.js
> +        compiler.close();
` compiler.close(() => { process.exit(0) });`

2021-08-25 11:26 UTC, alexander-akait commented on packages/webpack-cli/lib/webpack-cli.js
> +      compiler.close();
We need test on `130` code here

2021-08-25 11:27 UTC, alexander-akait reviewed
Also let's add test on 130 code and close for serve (it is already implemented in dev server)

2021-08-25 14:11 UTC, alexander-akait reviewed
Looks good, let's add tests for `build`/`watch`/`serve`, just enable logging and check on https://github.com/webpack/webpack/blob/main/lib/cache/PackFileCacheStrategy.js#L1263 or you can implement custom plugin and use `compiler.cache.hooks.shutdown.tapPromise()` with `{ stage: 9999 }` to ensure we will run after cache was stored

2021-08-29 17:01 UTC, evenstensberg approved these changes

2021-08-30 12:02 UTC, alexander-akait commented
I will add tests

2021-09-06 17:41 UTC, alexander-akait commented
@snitin315 We need improve logic here: we need allow to graceful close and allow immutability disable, my idea - when developer run `CTRL + C` we try to `close()`, if `CTRL + C` pressed again we close immediately, also we need handle ` const signals = ["SIGINT", "SIGTERM"];` signals, for `serve` we need disable `setupExitSignals` and move this logic here https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1088 (in future major release we will remove this option, because it is wrong place for this, developer should handle closing manually)

2021-09-07 11:24 UTC, snitin315 commented
Makes sense, I will update it in near future.

2023-03-06 09:42 UTC, alexander-akait commented
@snitin315 hello, let's finish, just copy logic from dev server

2023-03-06 09:52 UTC, snitin315 commented
@alexander-akait sure 👍🏻

2023-08-27 12:56 UTC, evenstensberg requested changes
Could you rebase?

2023-11-19 21:39 UTC, evenstensberg commented on packages/serve/src/index.ts
> +          Promise.all(
I'd love to make this a variable and passing the variable to the promise expression

2024-04-10 15:11 UTC, closed without merging