Fix WEBPACK_DEV_SERVER_PACKAGE path check
webpack/webpack-cli pull request #3161
Opened 2022-03-13 13:10 UTC by solsson

**What kind of change does this PR introduce?**

Bugfix

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

Yes

**Summary**

Firstly this change fixes an issue that looks like a copy-paste error: Custom WEBPACK_DEV_SERVER_PACKAGE would be conditioned on WEBPACK_PACKAGE to exist.

The next change, using require.resolve, widens the usefulness of the override. With plain `existsSync` you basically need an absolute path, unless you know what the current working directory will be when using the override.

**Does this PR introduce a breaking change?**

I don't think so. Existing WEBPACK_PACKAGE or WEBPACK_DEV_SERVER_PACKAGE would have satisfied `fs.existsSync(require.resolve(path)))` if they worked.

**Other information**

2022-03-13 13:12 UTC, alexander-akait commented
Thanks, can you accept CLA?

2022-03-13 13:16 UTC, solsson commented
CLA signed.

Actually if the `existsSync` check causes any issues I'd be in favor of dropping it. These envs have distinct names that are unlikely to collide with other use of evns. Silently dropping them might cause more confusion than attempting the require regardless of value.

2022-03-13 15:15 UTC, solsson commented
I will force push to only the first commit, then get one commit at a time through CI.

2022-03-14 00:59 UTC, snitin315 commented
@solsson can you fix lint?

2022-03-14 06:42 UTC, rishabh3112 requested changes
Looks good, we need to fix lint and types as well.

2022-03-14 08:55 UTC, alexander-akait commented on packages/webpack-cli/src/webpack-cli.ts
> +        if (dependency === WEBPACK_PACKAGE && WEBPACK_PACKAGE_IS_CUSTOM) {
I think we should use `require.resolve()` here and improve error reporting here (same for below) if package was not found

2023-04-29 19:56 UTC, alexander-akait commented
@solsson Hello, do you have time to finish this PR? Because it is easy to fix lint, thank you

2023-06-04 00:52 UTC, closed without merging