chore: update dockerfile
webpack/webpack-cli pull request #3244
Opened 2022-05-14 19:00 UTC by evenstensberg

**What kind of change does this PR introduce?**

Updating deps

**Did you add tests for your changes?**
N/A

**If relevant, did you update the documentation?**
N/A
**Summary**
Updates to node v18

**Does this PR introduce a breaking change?**

No

**Other information**
N/A

2022-05-15 03:10 UTC, snitin315 commented on .devcontainer/Dockerfile
> +FROM node:18
16 is still LTS

2022-05-15 11:58 UTC, evenstensberg commented on .devcontainer/Dockerfile
> +FROM node:18
Docs on this?

2022-05-15 12:27 UTC, snitin315 commented on .devcontainer/Dockerfile
> +FROM node:18
https://nodejs.org/en/

2022-06-26 06:49 UTC, rishabh3112 requested changes
I think we need to have overhead to updating this with every node release.
I have a simple solution in mind to fix it. Will be creating a PR.

2022-06-26 07:55 UTC, rishabh3112 commented
Superseded by #3311

2022-06-26 07:55 UTC, closed without merging

2022-06-26 07:55 UTC, rishabh3112 commented
Thanks